# such active yaml!
name: 'setup-yq'
description: 'Install a version of the venerable YQ tool'
inputs:
  yq-version:  # id of input
    description: 'What version of YQ to install'
    required: false
    default: '3.3.2'
  yq-url:
    description: 'The url to download YQ from'
    required: false
    default: 'https://github.com/mikefarah/yq/releases/download/{version}/yq_{platform}_{arch}'
runs:
  using: 'node20'
  main: 'dist/index.js'
icon: book-open
color: '#FFFF00'
